{
 "title": "JWT Pizza Traffic",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Pizza_Creation_Latency_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU/Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Memory_Usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "CPU_Usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "Latency_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Attempts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rate(Valid_Logins_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "rate(Invalid_Logins_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(GET_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(PUT_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(POST_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(DELETE_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(Current_Revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "Active_Users_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Orders",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(Pizzas_Sold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(Pizza_Creation_Failures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}